version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
  - package-ecosystem: npm
    directory: "/docs"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "github.com/tendermint/tendermint"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    open-pull-requests-limit: 3
    labels:
      - dependencies
