version: '3'

services:
  kidnode0:
    container_name: kidnode0
    image: "tendermint/kidnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-kid.log}
    volumes:
      - ./build:/kid:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  kidnode1:
    container_name: kidnode1
    image: "tendermint/kidnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-kid.log}
    volumes:
      - ./build:/kid:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  kidnode2:
    container_name: kidnode2
    image: "tendermint/kidnode"
    environment:
      - ID=2
      - LOG=${LOG:-kid.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/kid:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  kidnode3:
    container_name: kidnode3
    image: "tendermint/kidnode"
    environment:
      - ID=3
      - LOG=${LOG:-kid.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/kid:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16

