---

- name: Fetch genesis.json
  fetch: "src=/home/kid/.kitools/config/genesis.json dest={{GENESISFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: kid

- name: Fetch config.toml
  fetch: "src=/home/kid/.kitools/config/config.toml dest={{CONFIGFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: kid

