---

- name: Copy binary
  copy:
    src: "{{KICLI_BINARY}}"
    dest: /usr/bin/kitoolscli
    mode: 0755
  notify: restart kitoolscli

- name: Copy service
  template:
    src: kitoolscli.service.j2
    dest: /etc/systemd/system/kitoolscli.service
  notify: systemctl

