on: [push, pull_request]
name: Build
jobs:

  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: go build ./...
