name: Run Gosec
on:
  pull_request:
    branches:
      - 2.0.x
      - 3.0.x
      - 4.0.x
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3.1.0
      - name: Run Gosec Security Scanner
        uses: informalsystems/gosec@master
        with:
          args: -exclude-dir=tests -exclude-dir=cmd ./...