name: Run Gosec
on:
  push:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3.0.2
      - name: Run Gosec Security Scanner
        uses: informalsystems/gosec@master
        with:
          args: -exclude-dir=tests ./...