name: Build & Test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/main'"

  test-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/setup-go@v2.2.0
        with:
          go-version: 1.18
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: Build Docker Image
        run: |
          make docker-build-debug
        if: env.GIT_DIFF
      - name: Test E2E
        run: |
          make test-e2e
        if: env.GIT_DIFF
